[package]
name = "bevy_dolly"
version = "0.0.1"
authors = ["Black Phlox <bphlox@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/BlackPhlox/bevy_dolly"
documentation = "https://docs.rs/bevy_dolly"
description = "The dolly abstraction layer for the bevy game framework"
keywords = ["gamedev", "bevy", "camera", "fps", "3d" ]
categories = ["game-development", "game-engines", ]
exclude = [
    "assets/*",
    ".github/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[lib]
name = "bevy_dolly"

[features]
default = ["drivers", "helpers"]
drivers = []
helpers = ["dep:leafwing-input-manager"]

[dependencies]
dolly = "0.4"
leafwing-input-manager = { version = "0.7", optional = true }

[dependencies.bevy]
git = "https://github.com/rpv-floriculture/bevy"
# path = "../bevy"
features = ["bevy_asset"]
default-features = false

[dev-dependencies]
leafwing-input-manager = "0.7"

[dev-dependencies.bevy]
git = "https://github.com/rpv-floriculture/bevy"
# path = "../bevy"
features = ["bevy_asset", "bevy_scene", "bevy_winit", "bevy_gltf", "png"]
default-features = false

[target.'cfg(target_os = "linux")'.dev-dependencies.bevy]
git = "https://github.com/rpv-floriculture/bevy"
# path = "../bevy"
features = ["x11", "wayland"]
default-features = false